/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EtfEtfCodeRouteImport } from './routes/etf/$etfCode'
import { Route as ApiSnapshotsSeriesRouteImport } from './routes/api/snapshots-series'
import { Route as ApiSnapshotsRouteImport } from './routes/api/snapshots'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiCaptureLogsRouteImport } from './routes/api/capture-logs'

const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EtfEtfCodeRoute = EtfEtfCodeRouteImport.update({
  id: '/etf/$etfCode',
  path: '/etf/$etfCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnapshotsSeriesRoute = ApiSnapshotsSeriesRouteImport.update({
  id: '/api/snapshots-series',
  path: '/api/snapshots-series',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnapshotsRoute = ApiSnapshotsRouteImport.update({
  id: '/api/snapshots',
  path: '/api/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaptureLogsRoute = ApiCaptureLogsRouteImport.update({
  id: '/api/capture-logs',
  path: '/api/capture-logs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/api/capture-logs': typeof ApiCaptureLogsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/snapshots': typeof ApiSnapshotsRoute
  '/api/snapshots-series': typeof ApiSnapshotsSeriesRoute
  '/etf/$etfCode': typeof EtfEtfCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/api/capture-logs': typeof ApiCaptureLogsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/snapshots': typeof ApiSnapshotsRoute
  '/api/snapshots-series': typeof ApiSnapshotsSeriesRoute
  '/etf/$etfCode': typeof EtfEtfCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/api/capture-logs': typeof ApiCaptureLogsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/snapshots': typeof ApiSnapshotsRoute
  '/api/snapshots-series': typeof ApiSnapshotsSeriesRoute
  '/etf/$etfCode': typeof EtfEtfCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/api/capture-logs'
    | '/api/config'
    | '/api/health'
    | '/api/snapshots'
    | '/api/snapshots-series'
    | '/etf/$etfCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/api/capture-logs'
    | '/api/config'
    | '/api/health'
    | '/api/snapshots'
    | '/api/snapshots-series'
    | '/etf/$etfCode'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/api/capture-logs'
    | '/api/config'
    | '/api/health'
    | '/api/snapshots'
    | '/api/snapshots-series'
    | '/etf/$etfCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  ApiCaptureLogsRoute: typeof ApiCaptureLogsRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSnapshotsRoute: typeof ApiSnapshotsRoute
  ApiSnapshotsSeriesRoute: typeof ApiSnapshotsSeriesRoute
  EtfEtfCodeRoute: typeof EtfEtfCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etf/$etfCode': {
      id: '/etf/$etfCode'
      path: '/etf/$etfCode'
      fullPath: '/etf/$etfCode'
      preLoaderRoute: typeof EtfEtfCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snapshots-series': {
      id: '/api/snapshots-series'
      path: '/api/snapshots-series'
      fullPath: '/api/snapshots-series'
      preLoaderRoute: typeof ApiSnapshotsSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snapshots': {
      id: '/api/snapshots'
      path: '/api/snapshots'
      fullPath: '/api/snapshots'
      preLoaderRoute: typeof ApiSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/capture-logs': {
      id: '/api/capture-logs'
      path: '/api/capture-logs'
      fullPath: '/api/capture-logs'
      preLoaderRoute: typeof ApiCaptureLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  ApiCaptureLogsRoute: ApiCaptureLogsRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSnapshotsRoute: ApiSnapshotsRoute,
  ApiSnapshotsSeriesRoute: ApiSnapshotsSeriesRoute,
  EtfEtfCodeRoute: EtfEtfCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
